auto_part: Set disk capacity limitation to 60G
Change-Id: I7bb2d1bda55bd909b2f62512b75d48a2915deb9c

diff --git a/hooks/before_chroot/auto_part b/hooks/before_chroot/auto_part
--- a/hooks/before_chroot/auto_part
+++ b/hooks/before_chroot/auto_part
@@ -11,8 +11,14 @@
 echo "[$0]"
 set -x
 
+# Umount all swap partitions.
+swapoff -a
+
 # Path to installer configuration file.
 CONF_FILE='/etc/deepin-installer.conf'
+
+# Mimumum disk capacity required, 60G.
+MININUM_DISK_SIZE=61052
 
 cp -vf "/usr/share/deepin-installer/templates/lfs-atm.conf" $CONF_FILE
 # Remote group name. Group name starts with [
@@ -44,6 +50,11 @@ fi
 
 DEVICE_SIZE=$(blockdev --getsize64 $DEVICE)
 DEVICE_SIZE=$((DEVICE_SIZE / 1048576))
+if [ $DEVICE_SIZE < $MININUM_DISK_SIZE ]; then
+  echo 'Error: At least 60G is required to install!'
+  exit 1
+fi
+
 REMAINING_SIZE=$((DEVICE_SIZE - SWAP_SIZE))
 
 # 40% remaining space for /.
@@ -58,31 +69,31 @@ sed -i "s|DI_ROOT_DISK=.*$|DI_ROOT_DISK=\"$DEVICE\"|" $CONF_FILE
 
 # First create a msdos partition table.
 parted -s $DEVICE mktable msdos || \
-  (echo "Failed to create msdos partition on $DEVICE"; exit 1)
+  echo "Failed to create msdos partition on $DEVICE" && exit 1
 
 # Then create a swap partition with 4G.
 parted -s $DEVICE mkpart primary linux-swap 1M ${SWAP_SIZE}M || \
-  (echo "Failed to create linux-swap on ${DEVICE}1"; exit 1)
+  echo "Failed to create linux-swap on ${DEVICE}1" && exit 1
 mkswap ${DEVICE}1 || \
-  (echo "Failed to call mkswap ${DEVICE}1"; exit 1)
+  echo "Failed to call mkswap ${DEVICE}1" && exit 1
 
 # And then create an ext4 partition with 20G capacity to mount /var/log
 parted -s $DEVICE mkpart primary ext4 ${SWAP_SIZE}M ${ROOT_SIZE}M || \
-  (echo "Failed to create partition ${DEVICE}2"; exit 1)
+  echo "Failed to create partition ${DEVICE}2" && exit 1
 mkfs.ext4 -F ${DEVICE}2 || \
-  (echo "Failed to make ext4 filesystem on ${DEVICE}2"; exit 1)
+  echo "Failed to make ext4 filesystem on ${DEVICE}2" && exit 1
 sed -i "s|DI_ROOT_PARTITION=.*$|DI_ROOT_PARTITION=\"${DEVICE}2\"|" $CONF_FILE
 
 # Add 40% to /var/log, with ext4 type.
 parted -s $DEVICE mkpart primary ext4 ${ROOT_SIZE}M ${LOG_SIZE}M || \
-  (echo "Failed to create partition ${DEVICE}3"; exit 1)
+  echo "Failed to create partition ${DEVICE}3" && exit 1
 mkfs.ext4 -F ${DEVICE}3 || \
-  (echo "Failed to make ext4 filesystem on ${DEVICE}3"; exit 1)
+  echo "Failed to make ext4 filesystem on ${DEVICE}3" && exit 1
 sed -i "s|DI_MOUNTPOINTS=.*$|DI_MOUNTPOINTS=\"${DEVICE}1=swap;${DEVICE}3=/var/log;\"|" $CONF_FILE
 
 # All remaining space is used as backup partition.
 parted -s $DEVICE mkpart primary ext4 ${LOG_SIZE}M 100% || \
-  (echo "Failed to create partition ${DEVICE}4"; exit 1)
+  echo "Failed to create partition ${DEVICE}4" && exit 1
 mkfs.ext4 -F ${DEVICE}4
 
 # Commit to kernel.
